---
- name: Destroying MariaDB container
  docker_container:
    name: "mariadb-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Mount /database
  mount:
    path: /database
    src: tmpfs
    fstype: tmpfs
    state: unmounted

- name: Remove volumes
  file:
    state: absent
    path: "{{ item }}"
    force: yes
  with_items:
    - "/opt/local/etc/mysql.conf.d/"
    - "/database"
