---

# ---------------------------------------------- Setup rally
- name: Install rally result directory
  file: path=/root/rally_home state=directory owner=65500

- name: Test whether the rally database has been initialized
  stat: path=/root/rally_home/rally.db
  register: sqlite

- name: Initialize database
  when: not sqlite.stat.exists
  command: >
    docker run -v /root/rally_home:/home/rally/data xrally/xrally-openstack
           db create

# NOTE(msimonin): without the pause
# the file seems not to be synced in the next task.
# Relaunching the play a second time is also a possible wokaround.
- name: Waiting a few seconds
  pause: seconds=5

- name: Test whether the rally deployment has been created
  command: >
    docker run -v /root/rally_home:/home/rally/data xrally/xrally-openstack
           deployment list
  register: deployment

- name: Deploy discovery context
  when: "'discovery' not in deployment.stdout"
  docker_container:
    name: "rally-{{ inventory_hostname_short }}"
    image: "xrally/xrally-openstack"
    state: started
    volumes:
      - /root/rally_home:/home/rally/data
    env: "{{ os_env }}"
    command: deployment create --fromenv --name=discovery

# ----------------------------------- Setup & run rally test


- name: Run scenarios
  command: >
    docker run -v /root/rally_home:/home/rally/data xrally/xrally-openstack
           task start /home/rally/source/samples/tasks/scenarios/{{ item }}
           --deployment discovery
  with_items: "{{ rally_files }}"
  when: rally_files

- name: Run scenarios
  command: >
    docker run -v /root/rally_home:/home/rally/data xrally/xrally-openstack
           task start /home/rally/source/samples/tasks/scenarios/{{ item }}
           --deployment discovery
  with_items: "{{ rally_files }}"
  when: not rally_files

# -------------------------------- Download results (if any)
# - name: Find report identifier
#   shell: >
#     docker run -v /root/rally_home:/home/rally/data {{ rally_container_image }}\
#            task list --uuids-only\
#            --deployment discovery\
#           | tail -n 1
#   register: task_uuid

# - name: Generating rally reports (html) for {{ task_uuid.stdout }}
#   when: task_uuid.stdout != ""
#   command: >
#     docker run -v /root/rally_home:/home/rally/data {{ rally_container_image }}
#            task report --uuid {{ task_uuid.stdout }}
#            --html-static --out
#            /home/rally/data/report-{{ bench.scenario_location | basename }}-{{ task_uuid.stdout }}.html

# - name: Generating rally reports (json) for {{ task_uuid.stdout }}
#   when: task_uuid.stdout != ""
#   command: >
#     docker run -v /root/rally_home:/home/rally/data {{ rally_container_image }}
#            task report --uuid {{ task_uuid.stdout }}
#            --json --out
#            /home/rally/data/report-{{ bench.scenario_location | basename }}-{{ task_uuid.stdout }}.json
