---

- name: Remove containers
  shell: >
    docker rm $(docker ps -a | grep rally | grep -oEe '^([a-z]|[0-9]){12}')
  when:
    - '"rally" in tasks_ran'

- name: Remove volume
  command: >-
    rm -rf /root/rally_home/
  when:
    - '"rally" in tasks_ran'
