---

- name: Create the directories
  file:
    path: "/database/"
    state: directory

# See https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html

- name: Mount /database
  mount:
    path: /database
    src: tmpfs
    fstype: tmpfs
    state: mounted
    opts: size=16G

- name: Start the first cockroachdb node
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach:v2.0.1"
    # hostname: "{{ inventory_hostname }}"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - "/database:/cockroach/cockroach-data"
    command: >
      start --insecure
      --advertise-host="{{ hostvars[inventory_hostname]['ansible_'+ database_network]['ipv4']['address'] }}"
  when:
    - inventory_hostname == dbmaster_node

- name: Waiting for the first database to be ready
  wait_for:
    host: "{{ hostvars[dbmaster_node]['ansible_' + database_network]['ipv4']['address'] }}"
    port: 26257
  when:
    - inventory_hostname == dbmaster_node

- name: Start other cockroachdb nodes
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach:v2.0.1"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - "/database:/cockroach/cockroach-data"
    command: >
      start --insecure
      --join="{{ hostvars[dbmaster_node]['ansible_'+ database_network].ipv4.address }}"
      --advertise-host="{{ hostvars[inventory_hostname]['ansible_'+ database_network]['ipv4']['address'] }}"
  when:
    - inventory_hostname != dbmaster_node

- name: Waiting for databases to be ready
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + database_network]['ipv4']['address'] }}"
    port: 26257
  when:
    - inventory_hostname != dbmaster_node
