---

# See https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html
# See https://www.cockroachlabs.com/docs/stable/demo-follow-the-workload.html for locality

- name: Start cockroachdb master
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach"
    hostname: "{{ inventory_hostname }}"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    command: start --insecure --advertise-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}" {% if locality %} --locality=region="{{inventory_hostname_short}}"{% endif %}
  when:
    - inventory_hostname == dbmaster_node

- name: Start cockroachdb slaves
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    command: start --insecure --join="{{ hostvars[dbmaster_node]['ansible_' + control_network]['ipv4']['address'] }}" --advertise-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}"{% if locality %} --locality=region="{{inventory_hostname_short}}"{% endif %}
  when:
    - inventory_hostname != dbmaster_node

- name: Waiting for the databases to be ready
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}"
    port: 26257
