---
- name: Start cockroachdb master
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach"
    hostname: "{{ inventory_hostname }}"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    command: start --insecure --advertise-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}"
  when:
    - inventory_hostname == dbmaster_node
    - not locality

- name: Start cockroachdb slaves
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    command: start --insecure --join="{{ hostvars[dbmaster_node]['ansible_' + control_network]['ipv4']['address'] }}" --advertise-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}"
  when:
    - inventory_hostname != dbmaster_node
    - not locality

- name: Start cockroachdb master with locality
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach"
    hostname: "{{ inventory_hostname }}"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    command: start --insecure --advertise-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}" --locality=region="{{ inventory_hostname_short }}"
  when:
    - inventory_hostname == dbmaster_node
    - locality

- name: Start cockroachdb slaves with locality
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach"
    detach: True
    ports:
      - 26257:26257
      - 8080:8080
    command: start --insecure --join="{{ hostvars[dbmaster_node]['ansible_' + control_network]['ipv4']['address'] }}" --advertise-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}" --locality=region="{{ inventory_hostname_short }}"
  when:
    - inventory_hostname != dbmaster_node
    - locality
