---
- name: Destroying CockroachDB container
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    state: absent
    force_kill: yes

- name: Remove volumes
  file:
    state: absent
    path: "/tmp/cockroach-data"
