---

- name: Getting the docker logs
  shell: docker logs sysbench > /sysbench_logs.txt

- name: Fetching the logs
  fetch:
    src: /sysbench_logs.txt
    dest: "{{ backup_dir }}/sysbench_logs.txt"
    flat: yes
