---

  # MariaDB

- name: Prepare sysbench on MariaDB
  docker_container:
    name: "sysbench"
    image: "severalnines/sysbench"
    detach: True
    command: sysbench --db-driver=mysql --table-size=100000 --mysql-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}" --mysql-port=3306 --mysql-user=sbtest --mysql-password=sbtest oltp_read_write prepare
  when:
    - db == 'mariadb'
    - inventory_hostname == dbmaster_node

- name: Run sysbench on MariaDB
  docker_container:
    name: "sysbench"
    image: "severalnines/sysbench"
    detach: True
    command: sysbench --db-driver=mysql --table-size=100000 --mysql-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}" --mysql-port=3306 --mysql-user=sbtest --mysql-password=sbtest oltp_read_write run
  when:
    - db == 'mariadb'
    - inventory_hostname == dbmaster_node


  # CockroachDB

- name: Removes CockroachDB sbtest database for sysbench if present
  postgresql_db:
    name: sbtest
    login_host: "{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}"
    login_user: root
    port: 26257
    state: absent
  when:
    - db == 'cockroachdb'
    - inventory_hostname == dbmaster_node

- name: Create CockroachDB sbtest database for sysbench
  postgresql_db:
    name: sbtest
    login_host: "{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}"
    login_user: root
    port: 26257
    state: present
  when:
    - db == 'cockroachdb'
    - inventory_hostname == dbmaster_node

- name: Start sysbench on CockroachDB
  docker_container:
    name: "sysbench"
    image: "severalnines/sysbench"
    detach: True
    command: sysbench --db-driver=pgsql --pgsql-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}" --pgsql-port=26257 --pgsql-user=root --table-size=1000000 oltp_read_write prepare
  when: db == 'cockroachdb'

- name: Run sysbench on CockroachDB
  docker_container:
    name: "sysbench"
    image: "severalnines/sysbench"
    detach: True
    command: sysbench --db-driver=pgsql --pgsql-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}" --pgsql-port=26257 --pgsql-user=root --table-size=1000000 oltp_read_write run
  when: db == 'cockroachdb'
