---

  # MariaDB

- name: Creating sbtest user for sysbench
  mysql_user:
    name: sbtest
    password: sbtest
    host: "%"
    login_user: root
    login_password: my-secret-pw
    login_host: "{{ hostvars[inventory_hostname]['ansible_' + database_network]['ipv4']['address'] }}"
    priv: '*.*:ALL,GRANT'

- name: Removes MariaDB sbtest database for sysbench if present
  mysql_db:
    name: sbtest
    login_host: "{{ hostvars[inventory_hostname]['ansible_' + database_network]['ipv4']['address'] }}"
    login_user: sbtest
    login_password: sbtest
    state: absent

- name: Create MariaDB sbtest database for sysbench
  mysql_db:
    name: sbtest
    login_host: "{{ hostvars[inventory_hostname]['ansible_' + database_network]['ipv4']['address'] }}"
    login_user: sbtest
    login_password: sbtest
    state: present

- name: Prepare sysbench on MariaDB
  docker_container:
    name: "sysbench"
    image: "severalnines/sysbench"
    detach: False
    command: sysbench --db-driver=mysql --table-size=1000000 --mysql-host="{{ hostvars[inventory_hostname]['ansible_' + database_network]['ipv4']['address'] }}" --mysql-port=3306 --mysql-user=sbtest --mysql-password=sbtest oltp_read_write prepare

- name: Run sysbench on MariaDB
  docker_container:
    name: "sysbench"
    image: "severalnines/sysbench"
    detach: False
    command: sysbench --db-driver=mysql --table-size=1000000 --mysql-host="{{ hostvars[inventory_hostname]['ansible_' + database_network]['ipv4']['address'] }}" --mysql-port=3306 --mysql-user=sbtest --mysql-password=sbtest oltp_read_write run
