---
- name: Common configuration
  hosts: all
  roles:
    - common

- name: Install registry
  hosts: control
  roles :
    - registry

- name: Apply role chrony
  hosts: all
  roles:
    - chrony

- name: Deploy influx
  hosts: control
  roles:
    - influxdb

- name: Deploy the grafana
  hosts: control
  roles:
    - grafana

- name: CockroachDB master deployment
  hosts:
    - database
  roles:
    - { role: cockroachdb,
        when: db == "cockroachdb" }

- name: MariaDB master deployment
  hosts:
    - database
  roles:
    - { role: mariadb,
        when: db == "mariadb" }

- name: Install monitoring agents
  hosts: database
  roles:
    - { role: cadvisor }
    - { role: collectd,
        when: db == "mariadb" }
