---
- name: Common configuration
  hosts: all
  roles:
    - common
    - registry
    # - telegraf

- name: Apply role chrony
  hosts:
    - chrony-server
    - chrony
  roles:
    - chrony

- name: Deploy influx
  hosts: influxdb
  roles:
    - influxdb

# - name: Deploy the grafana
#   hosts: grafana
#   roles:
#     - grafana

- name: CockroachDB master deployment
  hosts:
    - database
  roles:
    - { role: cockroachdb,
        when: db == "cockroachdb" }

- name: MariaDB master deployment
  hosts:
    - database
  roles:
    - { role: mariadb,
        when: db == "mariadb" }
