---
- name: Common configuration
  hosts: all
  roles:
    - common
    - registry
    - telegraf

- name: Apply role chrony
  hosts:
    - chrony-server
    - chrony
  roles:
    - chrony

- name: Deploy influx
  hosts: influxdb
  roles:
    - influxdb

- name: Deploy the grafana
  hosts: grafana
  roles:
    - grafana

- name: CockroachDB master deployment
  hosts:
    - db-master
  roles:
    - { role: cockroachdb-master,
        when: db == "cockroachdb" }

- name: CockroachDB deployment
  hosts:
    - db-slave
  roles:
    - { role: cockroachdb,
        when: db == "cockroachdb" }

- name: MariaDB master deployment
  hosts:
    - db-master
  roles:
    - { role: mariadb-master,
        when: db == "mariadb" }

- name: MariaDB deployment
  hosts:
    - db-slave
  roles:
    - { role: mariadb,
        when: db == "mariadb" }

- name: Deploy sysbench
  hosts: sysbench
  roles:
    - sysbench
